name: Mac tests

on:
  # This avoids having duplicate builds for a pull request
  push:
    branches:
    - master
    - 5.x
    - 4.x
  pull_request:
    branches:
    - master
    - 5.x
    - 4.x

jobs:
  cleanup-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  build:
    name: Py${{ matrix.PYTHON_VERSION }}, ${{ matrix.INSTALL_TYPE }}, ${{ matrix.TEST_TYPE }}
    needs: cleanup-previous-runs
    runs-on: macos-latest
    env:
      CI: 'true'
      CODECOV_TOKEN: "56731c25-9b1f-4340-8b58-35739bfbc52d"
      OS: 'macos'
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUN_SLOW: ${{ matrix.TEST_TYPE == 'slow' }}
      USE_CONDA: ${{ matrix.INSTALL_TYPE == 'conda' }}
    strategy:
      fail-fast: false
      matrix:
        INSTALL_TYPE: ['conda']
        PYTHON_VERSION: ['3.7', '2.7']
        TEST_TYPE: ['fast', 'slow']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch branches
        run: git fetch --prune --unshallow
      - name: Check build skips
        shell: bash -l {0}
        run: |
          source .github/scripts/check_skip.sh
          source .github/scripts/check_skip_py.sh
      - name: Install Conda
        if: env.RUN_BUILD == 'true' && env.RUN_BUILD_PY == 'true'
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           auto-update-conda: true
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Create test environment
        if: env.RUN_BUILD == 'true' && env.RUN_BUILD_PY == 'true'
        shell: bash -l {0}
        run: bash -l .github/scripts/install.sh
      - name: Show test environment
        if: env.RUN_BUILD == 'true' && env.RUN_BUILD_PY == 'true'
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run manifest checks
        if: env.RUN_BUILD == 'true' && env.RUN_BUILD_PY == 'true'
        shell: bash -l {0}
        run: check-manifest
      - name: Run tests
        if: env.RUN_BUILD == 'true' && env.RUN_BUILD_PY == 'true'
        shell: bash -l {0}
        run: python runtests.py || python runtests.py || python runtests.py || python runtests.py || python runtests.py
      - name: Coverage
        if: env.RUN_BUILD == 'true' && env.RUN_BUILD_PY == 'true'
        shell: bash -l {0}
        run: codecov
